spring:
  datasource:
    url: jdbc:postgresql://192.168.1.251:5432/test
    username: postgres
    password: kuluv2#2018
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      idle-timeout: 10000
      maximum-pool-size: 10
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    classpath*: debug
debug: false