logging:
  path: ${user.home}/logs/kulu-gas-deploy
  file:
    max-size: 50MB
server:
  port: 8081
spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    database-platform: cn.tpson.kulu.gas.common.db.dialect.JsonbPostgresDialect


