logging:
  path: ${user.home}/logs/kulu-dispatcher-deploy
  file:
    max-size: 50MB
server:
  port: 8081
  servlet:
    context-path: /agent
spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
#  application:
#    name: USERSERVICE
