debug: false

kuluagent:
  car:
    boss: 1
    worker: 0
    backlog: 1024
    port: 7081
    timeout: 3000
  watch:
    boss: 1
    worker: 0
    backlog: 1024
    port: 7083
    timeout: 3000

agent:
  url: