kuluagent:
  car:
    boss: 1
    worker: 0
    backlog: 1024
    port: 8888
    timeout: 3000
  watch:
    boss: 1
    worker: 0
    backlog: 1024
    port: 8887
    timeout: 3000

agent:
  url: http://localhost:8081/protocal

#多个地址用逗号隔开
kafka:
  servers: 192.168.1.252:9092
  topic:
    hexmsg: dispatcher.server.hexmsg        #设备消息
    active: dispatcher.server.active        #设备上下线状态

#redis
#spring:
#  redis:
#    database: 0
#    host: 192.168.1.251
#    port: 6379
#    password: kulu###2018
#    timeout: 60000ms
#    jedis:
#      pool:
#        max-active: 100
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 8