spring:
  datasource:
    url: jdbc:postgresql://182.61.20.179:5432/dispatcher
    username: postgres
    password: kuluv2#2018
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      idle-timeout: 10000
      maximum-pool-size: 200
      auto-commit: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  redis:
    database: 0
    host: 182.61.20.179
    port: 6379
    password: kulu###2018
    timeout: 60000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 8
        min-idle: 8
logging:
  level:
    cn.tpson.kulu: info
debug: false

mq:
  timeout: 30000