logging:
  path: ${user.home}/logs/dispatcher
  file:
    max-size: 50MB
  level:
    cn.tpson.*: info
server:
  port: 8081
#  servlet:
#    context-path: /dispatcher
spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
#  application:
#    name: USERSERVICE

